name: Generate HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Generate HTML
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          path: pages
          ref: pages
          ssh-key: ${{ secrets.KEY }}
          repository: iedon/iedon-net-frontend

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: |
          set -ex
          npm run build
          pushd pages
          git config user.email "bot@github.com"
          git config user.name "bot"
          git fetch --unshallow
          git reset --hard 3db3705148566c96400e7a712bbd301d00e81e1e
          git clean -fxd :/
          popd
          cp -rf dist/* pages/
          cp CNAME pages/
          cp -f 404.html pages/
          pushd pages
          git add .
          git commit --allow-empty -m "Generated at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push --force origin pages
          popd
          # keepalive
          pushd .
          git config user.email "bot@github.com"
          git config user.name "bot"
          git reset --soft HEAD
          git commit --allow-empty -m "[skip ci] keepalive at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push origin main
          git show --name-only |grep -Fq '[skip ci] keepalive at'
          git reset --soft HEAD~1
          git push --force origin main
          popd
